global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: my-app
    static_configs:
      - targets:
          - app:8080
    metrics_path: /q/metrics
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090
  - job_name: tempo
    static_configs:
      - targets:
          - tempo:3200
